### ISSUE TITLE
API Requests hide 500 errors without returning them

### ISSUE THREAD

**Issue by Jake-Convictional** [convictional/convictional-node#4]
Here is a current usage of the request package for communicating with the API:
```
request({
    url: apiUrl + '/users/' + record._id,
    headers: { 'Authorization': adminKey },
    method: 'PUT',
    json: record
}, (error, res, body) => {
    if (error) {
        reject(error)
    } else {
        resolve(body)
    }
})
```

The problem is that the `error` variable is only used for connection errors (the request package couldn't get through to the server). If the request gets through but the server itself returns a `500` response, this doesn't count as an error, so the promise succeeds, even though the intent of the request did not succeed.

The result is that applications who use our package can't properly detect if something goes wrong.

**Proposal**
Find each usage of the request package and add in this check:
```
if (error) {
    reject(error)
} else if (res.statusCode !== 200) { // or 201 for posts
    reject(new Error('A problem occurred with the server.'))
} else {
    resolve(body)
}

**Comment by rogerkirkness** [comment]
I agree with this, Matt had a similar point this morning dealing with status codes on response from the API. I might include the status code on the error message in the middle path. We might also want to explore Bugsnag or similar, that would mirror our client side logs onto the server.

**Comment by Jake-Convictional** [comment]
Makes sense, you could even include the entire response to be really verbose, then you get the status code as well. Something like: `reject(new Error('Request not successful. Response: ' + res))`
I've never used Bugsnag, but I imagine something like that could be great.

**Comment by rogerkirkness** [comment]
I think what Bugsnag does among other things is catch and post errors to the server from the client. 

I guess it's up to us in terms of how to handle error messages. It's nice for something like this to be able to just surface a human friendly error message from the return value. Passing the response could accomplish that or could just appear as a bunch of garbled JSON depending on the server pattern.

**Comment by Jake-Convictional** [comment]
Here's what I implemented in #6 
```
if (error) {
    reject(error)
} else if (res.statusCode !== 200) {
    if (body.error) {
        reject(new Error(body.error + ' Code: ' + res.statusCode))
    } else {
        reject(new Error('A problem occurred with the request. Code: ' + res.statusCode))
    }
} else {
    resolve(body)
}
```

**Comment by Jake-Convictional** [comment]
Based on the discussion in #6, we can use a library function to replicate this for all the other requests. I suggested a fairly complicated approach here:
https://github.com/convictional/convictional-node/pull/6#issuecomment-505642605

We might get a more straightforward implementation by switching to the [promise implementation of request](https://github.com/request/request-promise-native) or just by using the `.on('response')` approach to request, though it is somewhat nuanced and not well documented. I would vote promises

**Comment by rogerkirkness** [comment]
I vote promises too.

**Comment by rogerkirkness** [comment]
@devanshkejriwal this one is quick win, bulk changing how errors are handled in the NPM package.

**Comment by devanshkejriwal** [comment]
I'll get on this

**Comment by rogerkirkness** [comment]
Thank you. There's a few other quick ones we can get out of the way.

**Comment by devanshkejriwal** [comment]
Just to be clear, you want me to change this
<pre>
request({
          url: apiUrl + '/orders/' + id,
          headers: { 'Authorization': apiKey },
          method: 'GET'
        }, (error, res, body) => {
          if (error) {
            reject(error)
          } else {
            resolve(JSON.parse(body))
          }
 })
</pre>

to 
<pre>
request-promise({
          url: apiUrl + '/orders/' + id,
          headers: { 'Authorization': apiKey },
          method: 'GET'
 }) 
     .then(function (body) {
          resolve(JSON.parse(body))
     })
     .catch(handleError)
</pre>

I found this over [here](https://www.npmjs.com/package/request-promise#thenonfulfilled-onrejected)

**Comment by rogerkirkness** [comment]
I think it's more about catching any responses that aren't errors but do indicate a problem. Jake talks about how to handle that here: https://github.com/convictional/convictional-node/pull/6#issuecomment-505642605

Would probably reduce the number of lines a lot to just have a single function check if the right status code is returned (ie. <299) and otherwise throw and log what happened.

**Comment by devanshkejriwal** [comment]
Is there a way for me to test it? There is a lot of places I'll have to change the request to use my function. I want to make sure what I'm doing is right before I spend more time on changing the rest.

**Comment by rogerkirkness** [comment]
Good call. I'm not sure. At one point there were integration tests for all the functions in there. It might be easier just to include the conditional Jake had that checks for >201 status and throws, instead of changing the structure and having to test every endpoint. It could be done via the front end.

**Comment by devanshkejriwal** [comment]
True, but I was trying to use a function to make it modular. The same function jake had written. This one:

<pre>
request({
  url: apiUrl + '/handlers/stripe/billOrder',
  method: 'POST',
  headers: { 'Authorization': apiKey },
  json: {
    'orderId': orderId,
    'parentId': parentId,
    'customerEmail': customerEmail
  }
}, requestHandler(reject, (res, body) => {
    // Do whatever
    resolve(body)
}))

...

function requestHandler(reject, happyPath) {
    return (error, res, body) => {
        if (error) {
            reject(error)
        } else if (res.statusCode !== 200) {
            if (body.error) {
                reject(new Error(body.error + ' Code: ' + res.statusCode))
            } else {
                reject(new Error('A problem occurred with the request. Code: ' + res.statusCode))
            }
        } else {
            happyPath(res, body)
        }
    }
}
</pre>

So I put that function in lib/functions.js and tried to call it the same way jake did. Do you think there should be need to test that?

**Comment by rogerkirkness** [comment]
If it works for the implementation Jake had, then no, the only issue would
be endpoints that return other 200 series status codes (like Jake
mentioned, ie. 201). My suggestion is to check whether the status is less
than 299, if so consider it success, if not failure and throw.
